# Generated by Django 5.2.5 on 2025-08-26 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribucion',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='distribucion',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='distribucion',
            name='zona',
        ),
        migrations.AddField(
            model_name='distribucion',
            name='barrio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='estrato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='encuestador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_respuestas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
