# Generated by Django 5.2.5 on 2025-08-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_remove_distribucion_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribucion',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='distribucion',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], default='Masculino', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='genero',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True),
        ),
    ]
